FLIP_spoof_templates = [
    'This is an example of a spoof face',
    'This is an example of an attack face',
    'This is not a real face',
    'This is how a spoof face looks like',
    'a photo of a spoof face',
    'a printout shown to be a spoof face',
]

FLIP_real_templates = [
    'This is an example of a real face',
    'This is a bonafide face',
    'This is a real face',
    'This is how a real face looks like',
    'a photo of a real face',
    'This is not a spoof face',
]

TeG_DG_real_templates = [
    'A real photo of a person',
    'A genuine image of the person',
    'An actual snapshot of the individual',
    'A real-life photograph of the person',
    'A true-to-life photo of the person',
    'An authentic photograph of the individual',
    'A bona fide picture of the person',
    'An unedited photograph of the individual',
    'A legitimate snapshot of the person',
    'An original photo depicting the individual',
    'A veritable image of the person',
    'An unaltered photograph of the individual',
    'A factual representation in a photo of the person',
    'An honest capture of the individual’s likeness',
    'A straightforward photograph of the person',
    'An undistorted image of the individual',
    'An unembellished photograph of the individual',
    'A straightforward capture of the person’s appearance',
    'A direct shot of the individual, unmodified',
    'A candid photograph depicting the person',
    'A natural, unposed photo of the individual',
    'An unretouched image of the person',
    'A clear, unfiltered photograph of the individual',
    'A genuine representation in a photo of the person',
    'An honest, unadorned picture of the individual',
    'A pure, unedited image of the person',
    'A real, unmanipulated photograph of the individual',
    'A sincere, untouched snapshot of the person',
    'An exact, unaltered capture of the individual’s visage',
    'An unvarnished, true photo of the person',
    'An unexaggerated, straightforward image of the individual',
    'A plain, accurate photograph of the person',
    'A genuine, unaltered image of the person',
    'A truthful depiction in a photograph of the individual',
    'An unprocessed photo of the person',
    'A raw, natural shot of the individual',
    'A direct, unaltered photograph of the person',
    'A true, unfiltered image of the individual',
    'An unmanipulated representation in a photo of the person',
    'A straightforward, unedited picture of the individual',
    'An undisturbed, authentic photo of the person',
    'An original, unenhanced image of the individual',
    'A non-doctored photograph of the person',
    'A pure, straightforward shot of the individual',
    'An unsullied, genuine photograph of the person',
    'An uncropped, clear image of the individual',
    'A veracious, unaltered photo of the person',
    'A true representation in a snapshot of the individual',
    'An honest, unfiltered view of the person',
    'A direct, unmanipulated photo of the individual',
    'A natural, unaltered image of the person',
    'An untouched, true-to-form photograph of the individual',
    'A straightforward, unenhanced snapshot of the person',
    'An unedited, authentic image of the individual',
    'A clear-cut, unadulterated photo of the person',
    'A non-altered, genuine representation of the individual',
    'A raw, unfiltered capture of the person',
    'An unadorned, straightforward picture of the individual',
    'A pure, unvarnished image of the person',
    'An honest, unprocessed photograph of the individual',
    'A direct, undistorted snapshot of the person',
    'An unedited, clear depiction of the individual',
    'A truthful, unaltered photo of the person',
    'An unenhanced, natural picture of the individual',
]

TeG_DG_spoof_templates = [
    'A counterfeit photo used in a print attack, not the actual person',
    'A fabricated image from a printout, falsely representing the individual',
    'A simulated snapshot used in a replay attack, impersonating the individual',
    'A deceptive photograph from a video replay, not the real-life person',
    'A manipulated photo in a print attack, falsely depicting the person',
    'An artificial photograph from a replay, masquerading as the individual',
    'A forged picture from a printout, wrongly showcasing the person',
    'A fake photograph used in a replay attack, imitating the individual',
    'A fraudulent snapshot from a printed image, falsely representing the person',
    'A mock-up photo in a video replay, feigning to be the individual',
    'A spurious image from a print attack, pretending to be the person',
    'A concocted photograph in a replay scenario, falsely imitating the individual',
    'A fictitious representation in a printed photo, not the genuine person',
    'A counterfeit capture from a replay attack, not truly the individual',
    'A deceptive shot from a printout, dishonestly representing the person',
    'A fabricated image in a video replay, not authentically the individual',
    'A simulated photograph from a print technique, not accurately the person',
    'A bogus snapshot in a replay deception, falsely depicting the individual',
    'A deceitful picture from a printed attack, impersonating the person',
    'A fake capture used in a replay fraud, wrongly showcasing the individual',
    'A phony photo from a print scheme, not truthfully the person',
    'A sham image in a video replay trick, falsely imitating the individual',
    'A counterfeit depiction from a print ruse, not the real person',
    'A fictive photograph in a replay deception, not genuinely the individual',
    'A pseudo snapshot from a printed trick, falsely representing the person',
    'A fabricated capture in a replay ruse, pretending to be the individual',
    'A misleading photo from a print forgery, not accurately the person',
    'A spurious image in a video replay fraud, wrongly depicting the individual',
    'A concocted shot from a print deception, not the true person',
    'A false photograph used in a replay trick, not authentically the individual',
    'A forged representation in a printed scam, misleadingly showcasing the person',
    'A mock-up image from a replay scheme, falsely claiming to be the individual',
    'A deceptive picture in a printout fraud, not honestly the person',
    'A bogus capture during a video replay scam, falsely portraying the individual',
    'A sham photo from a print attack, not the legitimate person',
    'A pseudo snapshot in a replay deceit, impersonating the individual',
    'A counterfeit image from a printout trick, not representing the real person',
    'A false photograph during a replay ruse, wrongly identifying the individual',
    'A manipulated shot from a printed forgery, not truly depicting the person',
    'A fictitious capture in a video replay deception, not the actual individual',
    'A fraudulent photo from a print scam, misleadingly representing the person',
    'A mock-up image in a replay fraud, not genuinely showcasing the individual',
    'A deceitful picture from a printout deceit, not the honest person',
    'A bogus snapshot during a video replay attack, falsely depicting the individual',
    'A synthetic photo from a printed trick, not truly the person',
    'A counterfeit capture in a replay scenario, not accurately the individual',
    'A fake representation from a printout scam, not genuinely the person',
    'A phony image during a replay trick, misleadingly imitating the individual',
    'A fabricated photo from a print deception, not truthfully the person',
    'A sham snapshot in a video replay ruse, falsely portraying the individual',
    'A pseudo picture from a printed attack, not the real-life person',
    'A spurious capture during a replay deceit, not truthfully the individual',
    'A concocted photograph from a print ruse, falsely claiming to be the person',
    'A fictive image in a replay fraud, not the genuine individual',
    'A misleading picture from a printout trick, falsely showcasing the person',
    'A bogus photo in a video replay scheme, not accurately depicting the individual',
    'A deceitful snapshot from a printed forgery, not the authentic person',
    'A fabricated capture in a replay attack, wrongly representing the individual',
    'A false representation in a printout fraud, misleadingly portraying the person',
    'A counterfeit image during a replay deception, not genuinely the individual',
    'A synthetic photograph from a print scam, not truthfully showcasing the person',
    'A sham shot in a video replay ruse, falsely claiming to be the individual',
    'A pseudo picture from a printout deceit, not honestly the person',
    'A spurious snapshot during a replay fraud, not accurately depicting the individual'
]

TeG_DG_print_templates = [
    'A printed photo',
    'A print attack photo',
    'A printed photo with is blur and lack of details',
    'A photo of an A4 paper with a face printed on it',
    'An image of an A4 sheet of paper bearing a printed face',
    'A photo of a paper printed with an image of a person',
    'A hard copy of a photograph',
    'A printed image on paper',
    'A blurred and indistinct printed photo',
    'A photograph depicting a face on an A4 sheet',
    'An A4 paper with a facial image printed upon it',
    'A paper bearing a printed photograph of an individual',
    'A printout of a photo with reduced clarity and detail',
    'An image of a person printed on standard paper',
    'A photo print, lacking sharpness and detail, on paper',
    'A snapshot printed on an A4-sized paper with a facial image',
    'A low-resolution printout of a face',
    'An image on paper, showing signs of being printed',
    'A photocopy of a photographic image',
    'A print of a digital photo, with visible pixelation',
    'A face image printed on a regular sheet of paper',
    'A printed photograph with faded colors',
    'A photo printout showing distortion',
    'A printed picture on a letter-sized paper',
    'An office printer output of a face photo',
    'A printed facial image with visible print lines',
    'A smudged photo printout on white paper',
    'A paper print of a digital image, showing compression artifacts',
    'A color print of a photograph, slightly blurred',
    'A printed image of a person with low contrast',
    'A printout of a portrait photo on plain paper',
    'A digitally printed photo with overexposure',
    'A facial photo printed using a home printer',
    'A printout of a photo, showing signs of ink spreading',
    'A printed image, lacking in fine details',
    'A photo on paper, with visible printing dots',
    'A printed portrait with a grainy texture',
    'A photo reproduction on matte paper',
    'A photocopy of a face, with some areas washed out',
    'A laser-printed image of an individual',
    'An inkjet printed photo with color misalignment',
    'A printed image, showing banding issues',
    'A paper print showing a digitally zoomed-in face',
    'A printed photo with noticeable color shifts',
    'A facial photograph printed on glossy paper',
    'A printout of a photo with a moiré pattern',
    'A printed face photo with a skewed perspective',
    'A color photo printed on a grayscale setting',
    'A photocopy of a person’s photo, with reduced saturation',
    'A printed image of a face, slightly off-center on the paper',
    'A photo print showing ink smears',
    'A printed image with a noticeable paper texture',
    'A photograph print with uneven ink distribution',
    'A printed photo, showing reduced dynamic range',
    'A face printout on textured paper',
    'A photo print with a yellowish tint',
    'A printed image of a person, cropped awkwardly',
    'A facial photo printed with low ink levels',
    'A digitally printed face with artifacts',
    'A printout of a photo with a watermark',
    'A printed photograph, slightly torn at the edge',
    'A print of a digital photo, with color bleeding',
    'A photo printed on thin, low-quality paper',
    'A printout of a face, showing digital noise'
]

TeG_DG_replay_templates = [
    'A replay attack photo',
    'A photo of an iPad',
    'A photo of an iPad that displaying face images',
    'A photo of a display',
    'A photo of a screen',
    'An image of a screen',
    'A photograph used for a replay attack',
    'An image of an iPad',
    'A photo showing an iPad displaying facial images',
    'A snapshot of a digital display screen',
    'A photograph capturing a computer or television screen',
    'An image depicting a monitor display',
    'A picture of a tablet screen showing a face',
    'A photograph of a device’s screen in operation',
    'An image depicting a monitor display',
    'A picture of a tablet screen showing a face',
    'A photo of a smartphone screen displaying an image',
    'An image of a laptop screen showing a face',
    'A snapshot showing a monitor with a facial image',
    'A photo of a device screen during a replay attack',
    'An image of a screen showing a video playback',
    'A photograph of a face displayed on a digital device',
    'A picture capturing a face on a tablet display',
    'A photo of a monitor screen with a facial portrait',
    'An image of a screen replaying a video',
    'A photograph showing a digital screen in use',
    'A snapshot of a face being displayed on a smartphone',
    'A photo of a computer monitor displaying images',
    'An image of a television screen in operation',
    'A picture of a digital display showing a live feed',
    'A photo of an electronic display with a static image',
    'An image capturing a tablet screen in operation',
    'A photograph of a screen showing a streaming video',
    'A snapshot of a digital billboard display',
    'A photo capturing a screen with multimedia content',
    'An image of a projected screen displaying a face',
    'A picture of a face on a high-resolution monitor',
    'A photo of a screen with high brightness showing a face',
    'An image of a LED display screen in action',
    'A photograph of a smartphone screen with a zoomed-in face',
    'A picture showing a monitor with a live webcam feed',
    'A snapshot of a TV screen showing a recorded video',
    'A photo of a video call in progress on a tablet',
    'An image showing a digital kiosk display',
    'A photograph of a computer screen with a face slideshow',
    'A picture of a mobile phone screen playing a video',
    'A photo showing a digital photo frame in use',
    'An image of a virtual reality screen displaying a face',
    'A picture showing a computer monitor with editing software',
    'A snapshot of an outdoor LED screen displaying an ad',
    'A photo of a tablet screen with a live streaming app',
    'An image of a monitor with a split-screen view',
    'A photograph of a phone screen showing a photo gallery',
    'A picture of a screen displaying interactive media',
    'A photo showing a touchscreen device in use',
    'An image of a monitor with screen mirroring active',
    'A photograph showing a tablet with a drawing app',
    'A picture of a laptop screen with a video conference',
    'A snapshot of a smartwatch screen with a notification',
    'A photo of a car display screen showing navigation',
    'An image of a screen with augmented reality content',
    'A photograph of a display with facial recognition software',
    'A picture of a screen displaying a 3D model of a face', 
    'A photo of a digital signboard showing a portrait'
]